// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/workspace" | "/workspace/agents" | "/workspace/agents/[agent_name]/chats/[thread_id]" | "/workspace/agents/new" | "/workspace/chats" | "/workspace/chats/[thread_id]" | "/workspace/chats/[thread_id]/control-room"
type AppRouteHandlerRoutes = "/api/auth/[...all]" | "/api/runtime/threads/[thread_id]/introspection" | "/mock/api/mcp/config" | "/mock/api/models" | "/mock/api/skills" | "/mock/api/threads/[thread_id]/artifacts/[[...artifact_path]]" | "/mock/api/threads/[thread_id]/history" | "/mock/api/threads/search"
type PageRoutes = never
type LayoutRoutes = "/" | "/workspace" | "/workspace/agents/[agent_name]/chats/[thread_id]" | "/workspace/chats/[thread_id]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/[...all]": { "all": string[]; }
  "/api/runtime/threads/[thread_id]/introspection": { "thread_id": string; }
  "/mock/api/mcp/config": {}
  "/mock/api/models": {}
  "/mock/api/skills": {}
  "/mock/api/threads/[thread_id]/artifacts/[[...artifact_path]]": { "thread_id": string; "artifact_path"?: string[]; }
  "/mock/api/threads/[thread_id]/history": { "thread_id": string; }
  "/mock/api/threads/search": {}
  "/workspace": {}
  "/workspace/agents": {}
  "/workspace/agents/[agent_name]/chats/[thread_id]": { "agent_name": string; "thread_id": string; }
  "/workspace/agents/new": {}
  "/workspace/chats": {}
  "/workspace/chats/[thread_id]": { "thread_id": string; }
  "/workspace/chats/[thread_id]/control-room": { "thread_id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/workspace": never
  "/workspace/agents/[agent_name]/chats/[thread_id]": never
  "/workspace/chats/[thread_id]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
