// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/agents/[agent_name]/chats/[thread_id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/agents/[agent_name]/chats/[thread_id]">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/agents/[agent_name]/chats/[thread_id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/agents/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/agents/new">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/agents/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/agents">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/chats/[thread_id]/control-room/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/chats/[thread_id]/control-room">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/chats/[thread_id]/control-room/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/chats/[thread_id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/chats/[thread_id]">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/chats/[thread_id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/chats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace/chats">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/chats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...all]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...all]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...all]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/runtime/threads/[thread_id]/introspection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runtime/threads/[thread_id]/introspection">> = Specific
  const handler = {} as typeof import("../../src/app/api/runtime/threads/[thread_id]/introspection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mock/api/mcp/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/mock/api/mcp/config">> = Specific
  const handler = {} as typeof import("../../src/app/mock/api/mcp/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mock/api/models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/mock/api/models">> = Specific
  const handler = {} as typeof import("../../src/app/mock/api/models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mock/api/skills/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/mock/api/skills">> = Specific
  const handler = {} as typeof import("../../src/app/mock/api/skills/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mock/api/threads/[thread_id]/artifacts/[[...artifact_path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/mock/api/threads/[thread_id]/artifacts/[[...artifact_path]]">> = Specific
  const handler = {} as typeof import("../../src/app/mock/api/threads/[thread_id]/artifacts/[[...artifact_path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mock/api/threads/[thread_id]/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/mock/api/threads/[thread_id]/history">> = Specific
  const handler = {} as typeof import("../../src/app/mock/api/threads/[thread_id]/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mock/api/threads/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/mock/api/threads/search">> = Specific
  const handler = {} as typeof import("../../src/app/mock/api/threads/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/agents/[agent_name]/chats/[thread_id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/workspace/agents/[agent_name]/chats/[thread_id]">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/agents/[agent_name]/chats/[thread_id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/chats/[thread_id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/workspace/chats/[thread_id]">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/chats/[thread_id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
